# Файл docker-compose должен начинаться с тега версии.
# Мы используем "3" так как это - самая свежая версия на момент написания этого кода.

version: "3"

services: 
  server:
    build: ./
    command: uvicorn server:app --reload --host 0.0.0.0 --port 81
    ports:
      - 81:81
